#!/bin/bash

THISDIR=~/bin       # this is the directory containing parser.py.

cd $THISDIR

if [ -e astro-ph.html ]
then
  rm -f astro-ph.html
fi

if [ -z "$1" ]
then
  ./astro-ph-parser
  OUTFN=`date '+20%y-%m-%d'`.html
else
  ./astro-ph-parser "$1"
  OUTFN=`date --date="$1" '+20%y-%m-%d'`.html
fi

if [ -e astro-ph.html ]
then
  scp -i /home/novak/.ssh/cron astro-ph.html publichost:public_html/astro-ph/$OUTFN
  if [ -z "$1" ] 
      then 
      scp -i /home/novak/.ssh/cron astro-ph.html publichost:public_html/astro-ph/index.html
  fi

  cd -
fi

exit 0
