#!/bin/bash 
RSYNC_RSH="/usr/bin/ssh -F /Users/novak/.ssh/config"
REMOTE_USER="novak"
#OPTS="--bwlimit=10 --archive --delete --delete-excluded --compress --verbose --progress --stats"
#OPTS="--archive --delete --delete-excluded --compress --verbose --progress --stats"
OPTS="--archive --delete --delete-excluded --verbose --progress --stats"
EXCLUDE=/Users/novak/bin/backup-laptop-exclude
DIRS=/Users/
#DEST=$REMOTE_USER@dionysus:/data/novak/Backup
DEST=$REMOTE_USER@publichost:\~/Crash-2005/sparse-laptop/

/usr/bin/rsync $OPTS --exclude-from=$EXCLUDE $DIRS $DEST

  