#!/bin/bash 
RSYNC_RSH="ssh -F /Users/novak/.ssh/config"
REMOTE_USER="novak"
#OPTS="--bwlimit=10 --archive --delete --delete-excluded --compress --verbose --progress --stats"
#OPTS="--archive --delete --delete-excluded --compress --verbose --progress --stats"
OPTS="--archive --delete --delete-excluded --verbose --progress --stats"
EXCLUDE=/Users/novak/bin/backup-laptop-exclude
DIRS=/Users/
DEST=$REMOTE_USER@dionysus:/data/novak/Backup

rsync $OPTS --exclude-from=$EXCLUDE $DIRS $DEST

  
