#!/usr/bin/perl
print "digraph packages {\n";
# screen
print "size=\"72,24\"\n";

#printer
#print "rotate=90\n";


print "node [fontname=luxirr];\n";

open STATUS, "/sw/var/lib/dpkg/status";

$first = 1;
$pack = "";
$stat = "";
$dep = "";
while (<STATUS>) {
    if (/^Package/) {	
	if (!$first) {
	    makenodes($pack,$stat,$dep);
	}
	else {
	    $first = 0;
	}
	$pack = $_;
	$stat = "";
	$dep = "";
    }
    if (/^Status:/) {
	$stat = $_;
    }
    if (/^Depends:/) {
	$dep = $_;
    }
}
print "\n}\n";

sub makenodes {
    my ($pack, $stat, $dep) = @_;
#    print "$pack$stat$dep\n";
    if ($stat =~ / installed/) {
	chomp $pack;
	$pack =~ s/Package://;
	$pack =~ s/\s//g;
	$pack =~ s/\W/_/g;
	chomp $dep;
	$dep =~ s/Depends://;
#	print "$dep\n"
	@dep = split(/[,|]/, $dep);
	foreach (@dep) {
	    s/\(.*\)//;
	    s/\s//g;
	    s/\W/_/g;
	    printline(" $pack -> $_ ;\n");
	}
    }
}

sub printline {
    my ($line) = @_;
    $line =~ s/_shlibs//g;
    $line =~ s/_dev//g;
    $line =~ s/_bin//g;
    if (!/x11/ &&
	!/dlcompat/ &&
	!/libjpeg/ &&
	!/gtk_/ &&
	!/gnome_libs/ &&
	!/libpng/ ) {
	print $line;
    }
}

