#!/usr/bin/perl

print "digraph packages {\n";
print "size=\"72,24\"\n";
print "node [fontname=luxirr];\n";

$package = shift(@ARGV);

open FILE, "fink-package-graph | grep \">.* $package \" | ";
@in = <FILE>;
close FILE;

foreach (@in) {
    print;
    $current = $_;
    chomp $current;
    $current =~ s/->.*//;
    $current =~ s/\s//g;

    $next = $_;
    chomp $next;
    $next =~ s/^.*->//;
    $next =~ s/;//;
    $next =~ s/\s//g;

    # need this to prevent infinite loop
    if (!($current eq $next)) {
	open FILE, "fink-package-graph | grep \">.* $current \" | ";
	@next = <FILE>;
	foreach (@next) {
	    push @in, $_;
	}
    }
}

print "\n}\n";
