#!/usr/bin/perl

chdir "/u/novak/bin";

$dayofweek = "Monday";
$room = "ISB 356";
$time = "12:30-1:30pm";

$soonwarning = 0;
$middlewarning = 3;
$farwarning = 7;

$talklist="gas.talks";
@reminders=qw(gas.rem1 gas.rem2 gas.rem3);
@announcements=qw(gas.ann1 gas.ann2);

$remsubjects[0]="Your GAS next week";
$remsubjects[1]="Your GAS on $dayofweek";
$remsubjects[2]="Your GAS today!";

$annsubjects[0]="GAS this $dayofweek";
$annsubjects[1]="GAS starting now!";

$grademail="grads allgood\@physics.ucsc.edu tcox\@physics.ucsc.edu";
$myemail = "novak";

# figure out the dates in the future
$soon=`echo 'puts [clock format [clock scan {$soonwarning days}] -format "%m/%d"]' | /opt/bin/tclsh`;
$middle=`echo 'puts [clock format [clock scan {$middlewarning days}] -format "%m/%d"]' | /opt/bin/tclsh`;
$far=`echo 'puts [clock format [clock scan {$farwarning days}] -format "%m/%d"]' | /opt/bin/tclsh`;

chomp $soon;
chomp $middle;
chomp $far;

$remdates[0] = $far;
$remdates[1] = $middle;
$remdates[2] = $soon;

$anndates[0] = $middle;
$anndates[1] = $soon;

# Speaker Reminders
foreach $date (@remdates) {
    $reminder = shift @reminders;
    $subject = shift @remsubjects;
    open TALKS, "< $talklist" or die "Can't open file : $!";
    while (<TALKS>) {
	if (/$date/) {
	    chomp;
	    @talk = split(":");
	    $date = $talk[0];
	    $speakeremail = $talk[1];
	    $speakername = $talk[2];
	    $talkinfo = $talk[3];
	    open TEMPLATE, "< $reminder";
	    open MESSAGE, "| mail $speakeremail $myemail -s \"$subject\"";
	    while (<TEMPLATE>) {
		s/<date>/$date/g;
		s/<speakeremail>/$speakeremail/g;
		s/<speakername>/$speakername/g;  
		s/<info>/$talkinfo/g;	
		s/<room>/$room/g;
		s/<time>/$time/g;
		s/<dayofweek>/$dayofweek/g;
		print MESSAGE;
	    }
	    close TEMPLATE;
	    close MESSAGE;
	}
    } 
    close TALKS;
}
# Audience reminders
foreach $date (@anndates) {
    $announcement = shift @announcements;
    $subject = shift @annsubjects;
    open TALKS, "< $talklist" or die "Can't open file : $!";
    while (<TALKS>) {
	if (/$date/) {
	    chomp;
	    @talk = split(":");
	    $date = $talk[0];
	    $speakeremail = $talk[1];
	    $speakername = $talk[2];
	    $talkinfo = $talk[3];
	    open TEMPLATE, "< $announcement";
	    open MESSAGE, "| mail $grademail -s \"$subject\"";
	    while (<TEMPLATE>) {
		s/<date>/$date/g;
		s/<speakeremail>/$speakeremail/g;
		s/<speakername>/$speakername/g;  
		s/<info>/$talkinfo/g;	
		s/<room>/$room/g;
		s/<time>/$time/g;
		s/<dayofweek>/$dayofweek/g;
		print MESSAGE;
	    }
	    close TEMPLATE;
	    close MESSAGE;
	}
    } 
    close TALKS;
}

# finally, delete leftover file
# system "rm -f /u/novak/mail.record"
