#!/usr/bin/env perl 

use Date::Simple;

chdir "$ENV{'HOME'}/bin";

$soonwarning = 0;
$middlewarning = 3;
$farwarning = 7;
$veryfarwarning = 14;

$talklist="gas.talks";
$separator="#";

@reminders=qw(gas.rem1 gas.rem2 gas.rem3 gas.rem4);
@announcements=qw(gas.ann1 gas.ann2);

$remsubjects[0]="Your GAS next week";
$remsubjects[1]="Your GAS on <dayofweek>";
$remsubjects[2]="Your GAS today!";
$remsubjects[3]="Your GAS in two weeks";

$annsubjects[0]="GAS this <dayofweek>";
$annsubjects[1]="GAS starting now!";

$grademail="grads\@ucolick.org allgood\@physics.ucsc.edu";
$myemail = "novak\@ucolick.org";

# figure out the dates in the future
$today = Date::Simple->new;
$soon = $today + $soonwarning;
$middle = $today + $middlewarning;
$far = $today + $farwarning;
$veryfar = $today + $veryfarwarning;

$remdates[0] = $far;
$remdates[1] = $middle;
$remdates[2] = $soon;
$remdates[3] = $veryfar;

$anndates[0] = $middle;
$anndates[1] = $soon;

# Speaker Reminders
foreach $date (@remdates) {
    $reminder = shift @reminders;
    $dayofweek = `date -d $date +%A`;
    chomp $dayofweek;
    $prettydate = `date -d $date +"%A, %B %d,"`;
    chomp $prettydate;
    $subject = shift @remsubjects;
    $subject =~ s/<dayofweek>/$dayofweek/;
    open TALKS, "< $talklist" or die "Can't open file : $!";
    while (<TALKS>) {	
	if (/$date/) {
	    chomp;
	    @talk = split $separator;
	    $date = $talk[0];
	    $date =~ s/^-//;
	    $room = $talk[1];
	    $time = $talk[2];
	    $speakername = $talk[3];
	    $speakeremail = $talk[4];
	    $talkinfo = $talk[5];
	    open TEMPLATE, "< $reminder";
#	    open MESSAGE, " | mail novak\@dionysus.ucolick.org -s \"$subject\"";
	    open MESSAGE, "| mail $speakeremail $myemail -s \"$subject\"";
	    while (<TEMPLATE>) {
		s/<prettydate>/$prettydate/g;
		s/<speakeremail>/$speakeremail/g;
		s/<speakername>/$speakername/g;  
		s/<info>/$talkinfo/g;	
		s/<room>/$room/g;
		s/<time>/$time/g;
		s/<dayofweek>/$dayofweek/g;
		print MESSAGE;
	    }
	    close TEMPLATE;
	    close MESSAGE;
	}
    } 
    close TALKS;
}
# Audience reminders
foreach $date (@anndates) {
    $announcement = shift @announcements;
    $dayofweek = `date -d $date +%A`;
    chomp $dayofweek;
    $prettydate = `date -d $date +"%A, %B %d,"`;
    chomp $prettydate;
    $subject = shift @annsubjects;
    $subject =~ s/<dayofweek>/$dayofweek/;
    open TALKS, "< $talklist" or die "Can't open file : $!";
    while (<TALKS>) {
	if (/$date/) {
	    chomp;
	    @talk = split $separator;
	    $date = $talk[0];
	    $date =~ s/^-//;
	    $room = $talk[1];
	    $time = $talk[2];
	    $speakername = $talk[3];
	    $speakeremail = $talk[4];
	    $talkinfo = $talk[5];
	    open TEMPLATE, "< $announcement";
#	    open MESSAGE, " | mail novak\@dionysus.ucolick.org -s \"$subject\"";
	    open MESSAGE, "| mail $grademail -s \"$subject\"";
	    while (<TEMPLATE>) {
		s/<prettydate>/$prettydate/g;
		s/<speakeremail>/$speakeremail/g;
		s/<speakername>/$speakername/g;  
		s/<info>/$talkinfo/g;	
		s/<room>/$room/g;
		s/<time>/$time/g;
		s/<dayofweek>/$dayofweek/g;
		print MESSAGE;
	    }
	    close TEMPLATE;
	    close MESSAGE;
	}
    } 
    close TALKS;
}

# finally, delete leftover file
#system "rm -f /u/novak/mail.record"
