#!/usr/bin/perl 

use Date::Simple;
use HTML::Template;

$dayofweeks = "Thursdays";
$room = "ISB 356";
$time = "12:30pm";

$separator = "#";
$infofile = "gas.talks";

chdir "$ENV{'HOME'}/bin";

$templateFile = "gas-web.thtml";
$outputFile = "gas-web.html";
#$publishcommand = "scp $outputFile publichost:public_html/Gas/index.html";

@alltalks = Gettalks($infofile);

@futuretalks = Futuretalks(@alltalks);
@pasttalks = Pasttalks(@alltalks);

$today = Date::Simple->new;
$modtime = $today->format("%c");

$template = HTML::Template->new(filename => $templateFile);
$future = Talklist(@futuretalks);
$past = Talklist(@pasttalks);

$template->param(
		 dayofweek => $dayofweeks,
		 room => $room,
		 time => $time,
		 futuretalks => $future,
		 pasttalks => $past,
		 modtime => $modtime,
		 );

open OUTFILE, "> $outputFile" || die "Can't open $outputfile!\n";
print OUTFILE $template->output;
close OUTFILE;

#system $publishcommand;

sub Talklist {
    my (@talks) = @_; 
    
    #@groups = ();
    $talklist = [()];

    foreach (@talks) {
	@talk = split $separator;
	$date = $talk[0];
	$date =~ s/^-//;
	$prettydate = `date -d $date +"%B %d"`;
	$room = $talk[1];
	$time = $talk[2];
	$speakername = $talk[3];
	$speakeremail = $talk[4];
	$talkinfo = $talk[5];
	push(@{$talklist}, { date => $prettydate,
			     name => $speakername, 
			     subject => $talkinfo,
		     });
    }
    return $talklist;
}

sub Gettalks {
    my ($fname) = @_;
    open INF, "< $fname" || die "Can't open $fname!\n";
    
    while (<INF>) {
	push @talks, $_;
    }
    return @talks;
}

sub Pasttalks {
    my (@talks) = @_; 
    $today = Date::Simple->new;
    foreach (@talks) {
	@talk = split $separator;
	$date = Date::Simple->new($talk[0]);
	if ($date < $today) {
	    push @pasttalks, $_;
	}
    }
    return @pasttalks;
}

sub Futuretalks {
    my (@talks) = @_; 
    $today = Date::Simple->new;
    foreach (@talks) {
	@talk = split $separator;
	$date = Date::Simple->new($talk[0]);
	if ($date >= $today) {
	    push @futuretalks, $_;
	}
    }
    return @futuretalks;
}
