#!/usr/bin/perl -w 
use HTTP::Request;
use LWP;

$ua = LWP::UserAgent->new;
$prefix = "a";

while (<>) {    
    chomp;
    $num = 1;
    $response = ($ua->request(HTTP::Request->new(GET => $_)))->content; 
    @response = split('\n',$response);
    $link = $_;
    $base = $link;
    $base =~ s+/[0-9A-z.]*$++;
    foreach(@response) {
	if (/mpg/) {
	    s/.*<a href=\"//;
	    s/\".*//g;
	    $url = "$base/$_";
	    $fn = $_;
	    $fn =~ s+.*/++;
	    $fn =~ s/10/a/;
	    $fn =~ s/11/b/;
	    $fn =~ s/12/c/;
	    $fn =~ s/13/d/;
	    $fn =~ s/14/e/;
	    $fn =~ s/15/f/;
	    $fn =~ s/16/g/;
	    $response = ($ua->request(HTTP::Request->new(GET => $url)))->content; 	    
	    print "Getting $prefix-$fn\n";
	    open(FILE, "> $prefix-$fn");
	    print FILE $response;
	    close(FILE);
	    $num++;
	}
    }
    system("mpgjoin $prefix-* -o $prefix.mpg");
    system("rm -f $prefix-*");
    $prefix++;
    print "Ready...\n";
}

