#!/usr/bin/env perl 

#$beg = "\\documentclass{article}\\usepackage{graphicx}\\setlength{\\textwidth}{6.5in}\\setlength{\\oddsidemargin}{0in}\\setlength{\\topmargin}{0in}\\setlength{\\headheight}{0in}\\setlength{\\headsep}{0in}\\setlength{\\topskip}{0in}\\setlength{\\textheight}{9.1in}\\begin{document}\n\n";
$beg = "\\documentclass{article}\\usepackage{graphicx}\\setlength{\\textwidth}{7.5in}\\setlength{\\oddsidemargin}{-0.5in}\\setlength{\\topmargin}{0in}\\setlength{\\headheight}{0in}\\setlength{\\headsep}{0in}\\setlength{\\topskip}{0in}\\setlength{\\textheight}{9.1in}\\begin{document}\n\n";
$plot = "\\includegraphics[width=<size>]{<file>}\n\n";
$end = "\\end{document}\n\n";

$size = shift(@ARGV);

print "Printing plots of size $size\n";

open(FILE, "| latex") || die "can't do it!\n";

print FILE $beg;
foreach (@ARGV) {
	$out = $plot;
	$out =~ s/<file>/$_/;
	$out =~ s/<size>/$size/;
	print FILE $out;
}
print FILE $end;

close(FILE) || die "can't close\n";
#system "dvips article.dvi -P simplex -o";
system "dvips article.dvi -o";
system "lpr article.ps";
system "rm -f article.ps";
system "rm -f article.aux article.dvi article.log";
