#!/usr/bin/perl

use File::Find;

if(@ARGV[0])
{
    while(@ARGV[0])
    {
	$f= pop @ARGV;
	process($f);
    }
}
else
{
    find(\&wanted, '.');
}

sub wanted
{
    $f = $_; # current filename

    if(!(-d $f))  # not a directory
    {
	if(substr($f,0,8) eq "snapshot")
	{
	   process($f);
	}

    }
}

sub process($f)
{
        $g= $f . ".pc";
	
	print "processing: ",$f,"\n";
	`swap-single_snapshot $f $g`;
	`swap-double-snapshot $g`;
	`mv $g $f`;
}














