#!/bin/env python
#!/usr/bin/env python

import sys, os.path

def main(argv=None):
    if argv is None: argv = sys.argv    

    nMax = 1000
    fnames = ['snapshot_%03d', 'snapshot_%04d']
    
    if len(argv) == 1:
        path = '.'
        n = nMax
    elif len(argv) == 2:
        n = int(argv[1])
        path = '.'
    elif len(argv) == 3:
        n = int(argv[1])
        path = argv[2]
    else:
        raise RuntimeError

    result = []
    for fname in fnames:
        try:
            for i in xrange(n+1):
                t = os.path.getctime(os.path.join(path, fname % i))
                t = os.path.getmtime(os.path.join(path, fname % i))
                result.append(t)
        except OSError:
            pass
        # Break the loop over possible snapshot filenames as soon as
        # you find some snapshots
        if len(result) > 0:
            break
    
    total = 0.0
    header = False
    #print [r -  result[0] for r in result]
    last1 = result[1]-result[0]
    k = []
    for i in range(len(result)-1):
        dt = result[i+1] - result[i]
        if dt > 3*last1:
            if not header:
                print "Breaks at",
                header = True
            print i+1, 
            total += last1
        else:
            total += dt
            last1 = dt

    if header: print ""
    print total/3600
            
if __name__ == '__main__':
    sys.exit(main())
