#!/usr/bin/env python
# If there are command line arguments, pass them
# otherwise, read from stdin and pass each line to osascript
# This is to facilitate use w/ socket and pipe
# first arg is browser, either safari or firefox

import sys,os

if len(sys.argv) > 2:
    for arg in sys.argv[2:]:
        os.system('osascript ~/bin/%s-open.scpt \'%s\'' % (sys.argv[1], arg))
else: 
    for url in iter(sys.stdin):
        os.system('osascript ~/bin/%s-open.scpt \'%s\'' % (sys.argv[1], url))
