#!/bin/bash
# comment
if [ "$#" = "0" ]; then 
	echo Usage - xmv dat dot 
	echo moves \*.dat to \*.dot
	exit
fi

if [ "$#" = "1" ]; then
	for OLDFILE in `ls *.$1`; do
		NEWFILE=`echo $OLDFILE | sed s/.$1$//g`
		mv $OLDFILE $NEWFILE
	done
fi

if [ "$#" = "2" ]; then
	for OLDFILE in `ls *.$1`; do
		NEWFILE=`echo $OLDFILE | sed s/.$1$/.$2/g`
		mv $OLDFILE $NEWFILE
	done
fi
